#!/bin/sh

### BEGIN INIT INFO
# Provides:           zsunray-init
# Required-Start:     $network $remote_fs gdm
# Required-Stop:      $network $remote_fs gdm
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Sun Ray Master init script
# Description:        Starts Sun Ray services (all of them from one place)
### END INIT INFO

NAME=zsunray-init
DESC="Sunray services"
case "$1" in
	start)
		[ ! -d /etc/X11/xdm ]  && mkdir -p /etc/X11/xdm
		[ ! -f /bin/awk ]      && ln -s /usr/bin/awk /bin/awk
		[ ! -f /bin/basename ] && ln -s /usr/bin/basename /bin/basename

		[ ! -d /tmp/.esd ] && mkdir /tmp/.esd
		chmod 1777 /tmp/.esd

		echo "Starting $DESC: $NAME"
		/etc/init.d/utacleanup start
		/etc/init.d/utds start
		/etc/init.d/utsyscfg start
		[ -x /etc/init.d/utstorage ] && /etc/init.d/utstorage start
		/etc/init.d/utsvc start

		chmod 666 /dev/dsp /dev/mixer
		sleep 2
		/etc/init.d/utwadmin start
		;;
	stop)
		echo "Stopping $DESC: $NAME "
		/etc/init.d/utwadmin stop
		/etc/init.d/utsvc stop
		[ -x /etc/init.d/utstorage ] && /etc/init.d/utstorage stop
		/etc/init.d/utacleanup stop
		/etc/init.d/utds stop
		/etc/init.d/utsyscfg stop
		sleep 3
		/usr/bin/pkill -9 Xnewt
		/usr/bin/pkill utaction
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0
